baseURL = 'https://www.vasiliauskas.com/'
languageCode = 'en-us'
title = 'Pete Vasiliauskas'

disableKinds = ['taxonomy', 'term']

[permalinks]
  articles = '/articles/:title/'
  posts = '/posts/:year/:month/:title/'

[Menus]
[[Menus.main]]
  Name = 'Articles'
  URL = '/articles/'
[[Menus.main]]
  Name = 'Posts'
  URL = '/posts/'
[[Menus.main]]
  Name = 'Resume'
  URL = '/resume/'

[imaging]
  quality = 75
  resampleFilter = 'Lanczos'
  [imaging.exif]
    disableDate = true
    disableLatLong = true

[markup]
  [markup.highlight]
    lineNos = true
    style = 'friendly'
